CREATE DATABASE PROJETO_LT;
USE PROJETO_LT;


CREATE TABLE SUPERVISOR (

  SUPER_ID    INTEGER      NOT NULL AUTO_INCREMENT,
  SUPER_NOME  VARCHAR(45)  NOT NULL,
  SUPER_EMAIL VARCHAR(255) NOT NULL,
  SUPER_SENHA VARCHAR(70)  NOT NULL,
  SUPER_TELE  VARCHAR(12)  NOT NULL,
  CONSTRAINT SUPER_ID_PK PRIMARY KEY (SUPER_ID)
);

CREATE TABLE USUARIO (

  USER_ID    INTEGER      NOT NULL AUTO_INCREMENT,
  USER_NOME  VARCHAR(45)  NOT NULL,
  USER_EMAIL VARCHAR(255) NOT NULL,
  USER_TELE  VARCHAR(13),
  USER_SENHA VARCHAR(70)  NOT NULL,
  CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID)

);

CREATE TABLE ATIVIDADE(
      ATV_ID INTEGER NOT NULL AUTO_INCREMENT,
      ATV_TEXTO VARCHAR(10000) NOT NULL,
      ATV_DATA DATE NOT NULL,
      CONSTRAINT ATV_PK PRIMARY KEY (ATV_ID)
);